### PR TITLE
Add quick sort algorithm

### PR DESCRIPTION
**Pull request by prantlf**

### CODE REVIEW

**Comment by prantlf** [comment]
Why, please?

**Comment by caspervonb** [comment]
@prantlf It was a weekend, after an all-nighter :wink:

**Comment by prantlf** [comment]
@caspervonb , I see. So you prefer to write the algorithms yourself and not just taking any ready implementation. No problem :-)

**Comment by caspervonb** [comment]
Been a couple of weeks now @prantlf but if I call correctly there was an issue with it and you had already closed the pull request by the time I saw it :disappointed: 

Thanks anyways tho :+1:

**Pull request closed without merging**
